### ISSUE TITLE
NullPointerException in 1.0.0 and 1.1.1

### ISSUE THREAD

**Issue by darinpantley** [jenkinsci/coordinator-plugin#31] opened 2016-04-13 22:37 UTC
I created 3 jobs:

jobA - This regular job is not parameterized and uses the Parameterized Trigger plugin to launch jobB with three Predefined Parameters.

jobB - This coordinator job accepts three parameters. The build tree has a Root node set to run sequentially and one child leaf referencing jobC.

jobC - This regular job accepts three parameters and then "echo"s each value to the log.

If I run jobB first, it successfully launches jobC.

If I run jobA first, it successfully runs jobB. The parameters I passed in are visible as environment variables in jobB. However, jobB fails to launch jobC with a NullPointerException.

Any idea why this is happening? I originally encountered this in 1.0.0. I manually upgraded to 1.1.1 (since it wasn't listed as an available upgrade on the plugins page), but it's still happening.

Here's the stack trace:

FATAL: null
java.lang.NullPointerException
	at org.jenkinsci.plugins.coordinator.model.PerformExecutor.prepareExecutionPlan(PerformExecutor.java:118)
	at org.jenkinsci.plugins.coordinator.model.PerformExecutor.execute(PerformExecutor.java:88)
	at org.jenkinsci.plugins.coordinator.model.CoordinatorBuilder.perform(CoordinatorBuilder.java:57)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:770)
	at hudson.model.Build$BuildExecution.build(Build.java:199)
	at hudson.model.Build$BuildExecution.doRun(Build.java:160)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:533)
	at hudson.model.Run.execute(Run.java:1745)
	at hudson.model.Build.run(Build.java:113)
	at hudson.model.ResourceController.execute(ResourceController.java:89)
	at hudson.model.Executor.run(Executor.java:240)

Thanks,
Darin

**Comment by ace-han** [comment] 2016-04-14 03:51
@darinpantley Could you provide the jobs settings as a zip file? like the one around https://github.com/jenkinsci/coordinator-plugin/issues/30#issuecomment-208839234

So that I could easily reproduce the problem you are facing, thx.

**Comment by ace-han** [comment] 2016-04-14 04:11
@darinpantley However, since `coordinator-plugin` is considered as a master controller over other jobs.

I don't know why you are using another regular job to trigger a master controller job.

From use case perspective, I think you could revise your job dependencies among jobs as a work around for the time being before my investigation with your zip file later on.

**Comment by ace-han** [comment] 2016-04-14 08:31
@darinpantley Thx for raising out this issue. Yes, it is a problem that persists all existing versions.

Fix has been pushed, and it will be available in release 1.2.0 which is target to release by next week.

So looking forward to that :smile:

**Closed** 2016-04-15 14:04 UTC
Labels: bug

**Comment by darinpantley** [comment] 2016-04-15 21:54
Thanks for fixing this so quickly!
